"""empty message

Revision ID: 5657db845143
Revises: 
Create Date: 2023-03-08 18:31:47.548578

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "5657db845143"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("players", schema=None) as batch_op:
        batch_op.alter_column(
            "id",
            existing_type=sa.INTEGER(),
            type_=sa.String(length=16),
            existing_nullable=False,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("players", schema=None) as batch_op:
        batch_op.alter_column(
            "id",
            existing_type=sa.String(length=16),
            type_=sa.INTEGER(),
            existing_nullable=False,
        )

    # ### end Alembic commands ###
